#!/bin/bash
#SBATCH --job-name=qunet_8_2_2
#SBATCH --output=qunet_8_2_2.out
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --time=8:00:00
#SBATCH --mem=32GB
#SBATCH --account=kalev_1005
#SBATCH --partition=epyc-64

echo "Starting Job: QuNet with 8 qubits, 2 filter, (2x2)x2 patches"
echo "----------------------------------------------------------"

python main_qunet_8_2_2.py > results/qunet/qunet_8_2_2/qunet_8_2_2.txt