#!/bin/bash
#SBATCH --job-name=qunet_12_2
#SBATCH --output=qunet_12_2.out
#SBATCH --ntasks=32
#SBATCH --cpus-per-task=1
#SBATCH --time=15:00:00
#SBATCH --mem=32GB
#SBATCH --account=kalev_1005
#SBATCH --partition=epyc-64

echo "Starting Job: QuNet with 12 qubits, 2 filter, 3x4 patches"
echo "----------------------------------------------------------"

python main_qunet_12_2.py > results/qunet/qunet_12_2/qunet_12_2_add.txt